name: PHPCS check

on: pull_request

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: composer install --dev --prefer-dist --no-progress --no-suggest
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
        with:
          installed_paths: '${{ github.workspace }}/vendor/escapestudios/symfony2-coding-standard'
